version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADDR: ":8080"
      DATABASE_URL: "postgres://app:app@db:5432/appdb?sslmode=disable"
    ports:
      - "8080:8080"
    # Uncomment next line to auto-restart in case of crash
    # restart: unless-stopped

volumes:
  db-data:
